"""Sword -> shield. Turn bastionprobe findings into agentbastion defenses.

Reads a results.jsonl (from `bastionprobe run --out`), takes only the payloads
that LANDED, and emits two artifacts agentbastion loads directly:

  policy.yaml       - the forbidden tools that got called, as a deny-list for
                      agentbastion's ToolPolicy (load_policy).
  injections.jsonl  - the injection strings that worked, in agentbastion's
                      corpus schema {text,label,category}. Feed them as custom
                      SemanticDetector templates (embedding similarity catches
                      the paraphrases too), and/or append to its benchmark corpus.

The loop: scan -> harden -> load both into agentbastion -> re-scan. Each round
the shield learns exactly what the sword got through.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Hardening:
    deny_tools: list[str]
    injections: list[dict]  # {text, label, category}, agentbastion corpus schema


def _clean_template(text: str) -> str:
    """The injection intent, minus bastionprobe's canary scaffolding, so it reads
    as a plain attack template for the semantic detector."""
    return " ".join(text.replace("{canary}", "").split())


def build_hardening(results_path: Path) -> Hardening:
    deny: list[str] = []
    seen_tools: set[str] = set()
    injections: list[dict] = []
    seen_text: set[str] = set()

    for line in results_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        r = json.loads(line)
        if not r.get("landed"):
            continue

        # forbidden tools that actually got called this run
        for tool in [r.get("forbidden_tool"), *r.get("tool_calls", [])]:
            if tool and tool not in seen_tools:
                seen_tools.add(tool)
                deny.append(tool)

        # the injection string that worked -> semantic template / corpus row
        template = _clean_template(r.get("payload_text", ""))
        if template and template not in seen_text:
            seen_text.add(template)
            injections.append(
                {"text": template, "label": "malicious", "category": r.get("category", "indirect_injection")}
            )

    return Hardening(deny_tools=deny, injections=injections)


def _policy_yaml(deny_tools: list[str]) -> str:
    # Hand-rolled to keep bastionprobe dependency-free. Drop-in shape: allow by
    # default, deny exactly what the sword got through. Tighten to default: deny
    # + an explicit allow-list for real lockdown.
    lines = [
        "# Generated by `bastionprobe harden` - tools an injection got to call.",
        "# Load in agentbastion: firewall.tool_policy = load_policy('policy.yaml')",
        "default: allow",
        "deny:",
    ]
    lines += [f"  - {t}" for t in deny_tools] or ["  []"]
    return "\n".join(lines) + "\n"


def write_hardening(h: Hardening, out_dir: Path) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    policy = out_dir / "policy.yaml"
    inj = out_dir / "injections.jsonl"
    policy.write_text(_policy_yaml(h.deny_tools), encoding="utf-8")
    with inj.open("w", encoding="utf-8") as f:
        for row in h.injections:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    return policy, inj


_WIRING = """\
Wire these into agentbastion:

  from agentbastion import Firewall, load_policy
  from agentbastion.semantic import SemanticDetector
  from agentbastion.inbound import InboundGuard
  import json

  templates = [json.loads(l)["text"] for l in open("{inj}", encoding="utf-8")]
  fw = Firewall()
  fw.tool_policy = load_policy("{policy}")                     # deny what got called
  fw.inbound = InboundGuard(detectors=[                        # block the injections
      SemanticDetector(your_embed_fn, templates=templates),   # + their paraphrases
  ])

Then re-run: bastionprobe run --out results2.jsonl  (fewer should land)
"""


def render_report(h: Hardening, policy: Path, inj: Path) -> str:
    if not h.deny_tools and not h.injections:
        return "Nothing landed - no hardening needed. The shield already holds."
    parts = [
        "",
        f"bastionprobe harden: {len(h.injections)} injection(s) -> {inj}",
        f"                     {len(h.deny_tools)} tool(s) to deny -> {policy}",
    ]
    if h.deny_tools:
        parts.append("  deny: " + ", ".join(h.deny_tools))
    parts.append("")
    parts.append(_WIRING.format(inj=inj.as_posix(), policy=policy.as_posix()))
    return "\n".join(parts)
